blueprint:
  name: Single Wall Switch controlling multiple independant entities with fixed scene
  description: |
    Use a single Wall Switch to Control several independant entities that could also potentially be controlled by other ways (Physical remotes, Wifi, Bluetooth, ...).

    If using a smart ON/OFF switch, this one cannot physically control a device as it will be used as a Toggle.

    The implementation proposed is the following:

        When the "Wall Switch Button" is pressed:
            if at least one entity defined in the "Restored Scene" is ON:
                => We consider the action is a Global switch OFF
                all entities are switched OFF
            else:
                => We consider theaction is a Global switch ON
                the "Restored Scene" is turned ON

  domain: automation
  input:
    button_switch:
      name: Wall Switch Button
      description: The binary sensor / input_button / button Wall Switch
      selector:
        entity:
          domain:
          - binary_sensor
          - input_button
          - button
    scene_restore_id:
      name: Restored Scene
      description: The scene to be turned ON on switch ON.
      selector:
        entity:
          domain:
          - scene

variables:
  scene_restore_id: !input scene_restore_id
  scene_entities_on: "{{ state_attr(scene_restore_id, 'entity_id') | select('is_state', 'on') | list }}"

triggers:
  - trigger: state
    entity_id: !input button_switch
    from: "off"
    to: "on"

conditions: []
actions:
  - if:
    - condition: template
      value_template: "{{ scene_entities_on | length > 0}}"
    then: # At least one entity is ON: Switch OFF
    - action: homeassistant.turn_off
      target:
        entity_id: "{{ scene_entities_on }}"
    else: # All Entities OFF: turn_on the scene
    - action: scene.turn_on
      data:
        entity_id: "{{ scene_restore_id }}"

mode: single
