blueprint:
  name: Single Wall Switch controlling multiple independant entities with scene
  description: |
    Use a single Wall Switch to Control several independant entities that could also potentially be controlled by other ways (Physical remotes, Wifi, Bluetooth, ...).

    If using a smart ON/OFF switch, this one cannot physically control a device as it will be used as a Toggle.

    There is no magic here: if you use a single button with only a 'single_press' action, or a ON/OFF switch, to control several entities there will be limitations.

    The implementation proposed is the following:

        When the "Wall Switch Button" is pressed:
            if at least one entity in "Always ON Entities", "Restored Entities" or "Non Restored Entities" is ON:
                => We consider the action is a Global switch OFF
                all entities are switched OFF
                the list of IDs of the "Restored Entities" that are ON at that moment is saved in a Text Input Helper
            else:
                => We consider theaction is a Global switch ON
                all "Always ON Entities" are switched ON
                all "Restored Entities" are switched ON if they are in the saved list

    If the entities are switched OFF by another way than the switch button (Remote, Wifi, ...), the list of entities to be restored is NOT Updated.
    The list of entities is kept in a dynamically created scene and as a consequence will be lost on HA restart / Scene reload
  domain: automation
  input:
    button_switch:
      name: Wall Switch Button
      description: The binary sensor / input_button / button Wall Switch
      selector:
        entity:
          domain:
          - binary_sensor
          - input_button
          - input_boolean
          - button
          - switch
    on_entities:
      name: Always ON Entities
      description: The entities that are always switched ON on switch ON
      default: []
      selector:
        entity:
          multiple: true
          domain:
          - light
          - fan
          - switch
    restored_entities:
      name: Restored entities
      description: The entities that are switched ON on switch ON ONLY if they where ON on last switch OFF
      selector:
        entity:
          multiple: true
          domain:
          - light
          - fan
          - switch
    non_restored_entities:
      name: Non Restored entities
      description: The entities that are NEVER switched ON on switch ON.
      default: []
      selector:
        entity:
          multiple: true
          domain:
          - light
          - fan
          - switch

variables:
  # Input variables
  on_entities: !input on_entities
  restored_entities: !input restored_entities
  non_restored_entities: !input non_restored_entities
  # Computed variables
  all_entities: "{{ on_entities + restored_entities + non_restored_entities }}"
  all_entities_on: "{{ all_entities | select('is_state', 'on') | list }}"
  restore_id: "restore_{{ this.entity_id.replace('.', '_') }}"
  scene_restore_id: "scene.{{ restore_id }}"

triggers:
  - trigger: state
    entity_id: !input button_switch

conditions: []
actions:
  - if:
    - condition: template
      value_template: "{{ all_entities_on | length > 0}}"
    then: # At least one entity is ON: Save state in scene and switch OFF
    - action: scene.create # or replace if exists
      data:
        scene_id: "{{ restore_id }}"
        snapshot_entities: "{{ restored_entities }}"
    - repeat:
        for_each: "{{ all_entities_on }}"
        sequence:
        - action: homeassistant.turn_off
          target:
            entity_id: "{{ repeat.item }}"
    else: # All Entities OFF: Switch ON the needed entities
    - repeat:
        for_each: "{{ on_entities }}"
        sequence:
        - action: homeassistant.turn_on
          target:
            entity_id: "{{ repeat.item }}"
    - if:
      - condition: template
        value_template: "{{ states[scene_restore_id] != None }}"
      then:
      - action: scene.turn_on
        data:
          entity_id: "{{ scene_restore_id }}"
      - action: scene.delete
        data:
          entity_id: "{{ scene_restore_id }}"


mode: single
